.TH GXSM 2 "February 22, 2002"
.SH NAME
vpdata2ascii \- part of Gnome X Scanning Microscopy (gxsm3 3.3.0)
.SH SYNOPSIS
.B vpdata2ascii
.RI " filetoread filetowrite xcol ycol "
.SH DESCRIPTION
Convert data from Vossplot to ASCII.
.TP
Part of the Gxsm (Gnome X Scanning Microscopy) suite.
.P
.SH COPYING
Copyright
.if t \(co 2005 - 2006 Percy Zahl, Andreas Klust
.PP
This is free software (GPL); see the source for copying conditions.  There
is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH AUTHORS
The project Gxsm was initiated by the main author Percy Zahl, see the
Gxsm Manual and homepage http://gxsm.sf.net for a complete list of
the contributors to the Gxsm project.
