# default geometry for GXSM4 WINDOW with title: Gxsm4
windowrule = float on, size 434 635, move (4) (41), match:class gxsm4, match:initial_title Gxsm4

# default geometry for GXSM4 WINDOW with title: Channel Selector
windowrule = float on, size 440 440, move (2) (679), match:class org.gnome.gxsm4, match:initial_title Channel Selector

# default geometry for GXSM4 WINDOW with title: RP-SPM Control Window
windowrule = float on, size 1534 791, move (448) (215), match:class org.gnome.gxsm4, match:initial_title RP-SPM Control Window

# default geometry for GXSM4 WINDOW with title: RPSPMC PACPLL Control for RedPitaya
windowrule = float on, size 1150 643, move (2496) (192), match:class org.gnome.gxsm4, match:initial_title RPSPMC PACPLL Control for RedPitaya

# default geometry for GXSM4 WINDOW with title: GXSM Activity Monitor and Logbook
windowrule = float on, size 1422 288, move (444) (1010), match:class org.gnome.gxsm4, match:initial_title GXSM Activity Monitor and Logbook

# default geometry for GXSM4 WINDOW with title: Pan View and OSD
windowrule = float on, size 241 241, move (2058) (45), match:class org.gnome.gxsm4, match:initial_title Pan View and OSD

# default geometry for GXSM4 WINDOW with title: HUD Probe Indicator
windowrule = float on, size 300 300, move (1760) (49), match:class org.gnome.gxsm4, match:initial_title HUD Probe Indicator

# default geometry for GXSM4 WINDOW with title: SPM Scan Control
windowrule = float on, size 423 331, move (1875) (960), match:class org.gnome.gxsm4, match:initial_title SPM Scan Control

# default geometry for GXSM4 WINDOW with title: Multi Dimensional Movie Control
windowrule = float on, size 440 177, move (4) (1118), match:class org.gnome.gxsm4, match:initial_title Multi Dimensional Movie Control

# default geometry for GXSM4 WINDOW with title: Python Remote Control Console
windowrule = float on, size 1029 694, move (3523) (569), match:class org.gnome.gxsm4, match:initial_title Python Remote Control Console



