# GXSM3
windowrule = float on, match:class ^(.*gxsm3)$

# GXSM4 tools,... static window geometry defaults
windowrule = float on, match:class ^(.*gxsm4)$

# HV5
windowrule = float on, size 1000 246, move (447) (223), match:class ^(com.createc.hv5app)$, match:title CHV5

### and some more

# Kitty
windowrule = float on, size 750 500, center on, opacity 0.80 0.60, match:class ^(kitty)$

windowrule = float on, size 1500 800, match:class ^(.*gedit)$

