set PROJ_NAME "project_RP-SPMC-PACPLL-4-GXSM4"

source make_cores.tcl

# Create the project and import the source files and set all project/file properties
# Create the block design inside of the project this file is autogenerated
#source rebuild.tcl

source recreate-rpspmc-pacpll-vivado-project.tcl

puts "Created $design_name"


