set PROJ_NAME "project_RP-SPMC-RedPACPLL-202308"

source make_cores.tcl

# Create the project and import the source files and set all project/file properties
# Create the block design inside of the project this file is autogenerated
source rebuild.tcl

puts "Created $design_name"


