#!/bin/sh
# Script to thumbnail "gmedat" files
size=`gconftool-2 -g /desktop/gnome/thumbnailers/application@x-netcdf/size 2> /dev/null`
if [ x$size == x ]
then
    size=120
fi
    
gmetopng --size=$size $1 $2
