usr/bin usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org/extension.js usr/bin usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org
usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org/metadata.json usr/bin usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org
usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org/stylesheet.css usr/bin usr/share/gnome-shell/extensions/gxsm-wm@gxsm4.gnome.org
