#!/bin/sh
# Script to thumbnail Omicron Scala files
size=`gconftool-2 -g /desktop/gnome/thumbnailers/application@x-omicron-scala/size 2> /dev/null`
if [ x$size == x ]
then
    size=120
fi
    
scalatopng --size=$size $1 $2
